development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: facebook_development
  pool: 5
  username: root
  password: root
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: facebook_production
  pool: 5
  username: root
  password: 
  host: localhost
